# Generated by Django 6.0.3 on 2026-03-07 13:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpaper',
            name='level',
            field=models.CharField(choices=[('L2', 'Level 2'), ('L3', 'Level 3'), ('L4', 'Level 4')], default='L2', max_length=2),
        ),
        migrations.AddField(
            model_name='video',
            name='level',
            field=models.CharField(choices=[('L2', 'Level 2'), ('L3', 'Level 3'), ('L4', 'Level 4')], default='L2', max_length=2),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='file',
            field=models.FileField(upload_to=core.models.paper_upload_path),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to=core.models.video_upload_path),
        ),
    ]
