# Generated by Django 6.0.3 on 2026-03-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pastpaper_level_video_level_alter_pastpaper_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper',
            name='level',
            field=models.CharField(choices=[('L2', 'Level 2'), ('L3', 'Level 3'), ('L4', 'Level 4')], max_length=2),
        ),
        migrations.AlterField(
            model_name='video',
            name='level',
            field=models.CharField(choices=[('L2', 'Level 2'), ('L3', 'Level 3'), ('L4', 'Level 4')], max_length=2),
        ),
    ]
