# Generated by Django 6.0.3 on 2026-03-08 20:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_file_pastpaper_paper_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='image',
        ),
        migrations.AddField(
            model_name='pastpaper',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='level',
            field=models.CharField(choices=[('L2', 'Level 2'), ('L3', 'Level 3'), ('L4', 'Level 4')], default='L2', max_length=2),
        ),
        migrations.AlterField(
            model_name='video',
            name='level',
            field=models.CharField(choices=[('L2', 'Level 2'), ('L3', 'Level 3'), ('L4', 'Level 4')], default='L2', max_length=2),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.video_upload_path),
        ),
    ]
